# Generated by Codex on 2026-07-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0002_public_contact_channels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="country",
            field=models.CharField(blank=True, default="France", max_length=120),
        ),
        migrations.AddField(
            model_name="publicemail",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="publicemail",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicemail",
            name="source_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="publicemail",
            name="verification_status",
            field=models.CharField(db_index=True, default="format_valid", max_length=30),
        ),
        migrations.AddField(
            model_name="publicphone",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="publicphone",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicphone",
            name="source_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="publicphone",
            name="verification_status",
            field=models.CharField(db_index=True, default="format_valid", max_length=30),
        ),
        migrations.CreateModel(
            name="EnrichmentSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("source_type", models.CharField(choices=[("public_registry", "Registre public"), ("company_website", "Site officiel"), ("public_page", "Page publique"), ("professional_directory", "Annuaire professionnel"), ("b2b_api", "API B2B"), ("user_import", "Import utilisateur"), ("open_web", "Web ouvert"), ("first_party", "Donnée propriétaire")], db_index=True, max_length=40)),
                ("enabled", models.BooleanField(default=True)),
                ("requires_api_key", models.BooleanField(default=False)),
                ("api_key_env", models.CharField(blank=True, max_length=120)),
                ("base_url", models.URLField(blank=True)),
                ("legal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["source_type", "name"]},
        ),
        migrations.CreateModel(
            name="EnrichmentRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("queued", "En attente"), ("running", "En cours"), ("done", "Terminé"), ("failed", "Échec")], db_index=True, default="queued", max_length=20)),
                ("mode", models.CharField(choices=[("prospect", "Fiche prospect"), ("search", "Recherche"), ("import", "Import")], default="prospect", max_length=20)),
                ("query", models.JSONField(blank=True, default=dict)),
                ("sources_requested", models.JSONField(blank=True, default=list)),
                ("sources_completed", models.JSONField(blank=True, default=list)),
                ("totals", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("prospect", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="enrichment_runs", to="prospects.prospect")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ProspectEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("field_name", models.CharField(db_index=True, max_length=80)),
                ("value", models.TextField()),
                ("normalized_value", models.CharField(blank=True, db_index=True, max_length=500)),
                ("value_type", models.CharField(choices=[("company", "Entreprise"), ("website", "Site web"), ("address", "Adresse"), ("email", "Email"), ("phone", "Téléphone"), ("person", "Contact"), ("profile", "Profil public"), ("other", "Autre")], default="other", max_length=30)),
                ("confidence_score", models.PositiveSmallIntegerField(db_index=True, default=50)),
                ("verification_status", models.CharField(choices=[("unverified", "Non vérifié"), ("format_valid", "Format valide"), ("deliverability_unknown", "Délivrabilité inconnue"), ("verified", "Vérifié"), ("invalid", "Invalide"), ("blocked", "Bloqué"), ("conflict", "Conflit")], db_index=True, default="unverified", max_length=30)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("is_current", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("prospect", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_items", to="prospects.prospect")),
                ("source", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="evidence_items", to="prospects.enrichmentsource")),
            ],
            options={"ordering": ["field_name", "-confidence_score", "-last_checked_at", "-collected_at"]},
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("full_name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=180)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("profile_url", models.URLField(blank=True, max_length=1000)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("confidence_score", models.PositiveSmallIntegerField(db_index=True, default=50)),
                ("verification_status", models.CharField(choices=[("unverified", "Non vérifié"), ("format_valid", "Format valide"), ("deliverability_unknown", "Délivrabilité inconnue"), ("verified", "Vérifié"), ("invalid", "Invalide"), ("blocked", "Bloqué"), ("conflict", "Conflit")], db_index=True, default="unverified", max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("prospect", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contact_people", to="prospects.prospect")),
                ("source", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contact_people", to="prospects.enrichmentsource")),
            ],
            options={"ordering": ["-confidence_score", "full_name", "email"]},
        ),
        migrations.AddConstraint(
            model_name="prospectevidence",
            constraint=models.UniqueConstraint(fields=("prospect", "field_name", "normalized_value"), name="unique_evidence_value_per_prospect"),
        ),
    ]
