# Generated by Django 5.2.4 on 2026-08-17 18:12

import django.db.models.deletion
import django.utils.timezone
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("prospects", "0003_enrichment_multisource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("behaviour_analytics", "Analyse comportementale"),
                            ("visitor_intelligence", "Intelligence visiteurs B2B"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("positioning", models.TextField(blank=True)),
                (
                    "relation_to_predictneed",
                    models.TextField(
                        blank=True,
                        help_text="Complémentaire, concurrent direct, adjacent...",
                    ),
                ),
                ("suggested_angle", models.TextField(blank=True)),
                ("scoring_penalty", models.SmallIntegerField(default=0)),
                ("scoring_bonus", models.SmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("active", models.BooleanField(default=True)),
                ("stop_on_reply", models.BooleanField(default=True)),
                ("stop_on_conversion", models.BooleanField(default=True)),
                ("stop_on_unsubscribe", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["product__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ICPProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("target_sectors", models.JSONField(blank=True, default=list)),
                ("naf_codes", models.JSONField(blank=True, default=list)),
                ("naf_sections", models.JSONField(blank=True, default=list)),
                ("company_categories", models.JSONField(blank=True, default=list)),
                ("employee_bands", models.JSONField(blank=True, default=list)),
                ("employee_min", models.PositiveIntegerField(blank=True, null=True)),
                ("employee_max", models.PositiveIntegerField(blank=True, null=True)),
                ("revenue_min", models.BigIntegerField(blank=True, null=True)),
                ("revenue_max", models.BigIntegerField(blank=True, null=True)),
                ("regions", models.JSONField(blank=True, default=list)),
                ("departments", models.JSONField(blank=True, default=list)),
                ("cities", models.JSONField(blank=True, default=list)),
                (
                    "min_company_age_years",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "max_company_age_years",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("required_signals", models.JSONField(blank=True, default=list)),
                ("positive_signals", models.JSONField(blank=True, default=list)),
                ("negative_signals", models.JSONField(blank=True, default=list)),
                ("excluded_signals", models.JSONField(blank=True, default=list)),
                ("excluded_domains", models.JSONField(blank=True, default=list)),
                ("excluded_sectors", models.JSONField(blank=True, default=list)),
                (
                    "weights",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Pondération icp_fit/need/acquisition_maturity/contactability/timing (somme=100).",
                    ),
                ),
                (
                    "minimum_outbound_score",
                    models.PositiveSmallIntegerField(default=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["product__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("website_url", models.URLField(blank=True)),
                ("simulator_url", models.URLField(blank=True)),
                ("signup_url", models.URLField(blank=True)),
                ("pricing_url", models.URLField(blank=True)),
                (
                    "monthly_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=8)),
                (
                    "short_value_proposition",
                    models.CharField(blank=True, max_length=280),
                ),
                ("long_value_proposition", models.TextField(blank=True)),
                ("target_problem", models.TextField(blank=True)),
                ("primary_cta_label", models.CharField(blank=True, max_length=120)),
                ("primary_cta_url", models.URLField(blank=True)),
                ("features", models.JSONField(blank=True, default=list)),
                ("differentiators", models.JSONField(blank=True, default=list)),
                ("competitor_notes", models.JSONField(blank=True, default=dict)),
                ("sender_brand_name", models.CharField(blank=True, max_length=160)),
                (
                    "sender_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom visible de l'expéditeur, ex. 'PredictNeed IA'.",
                        max_length=160,
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True,
                        help_text="Adresse From officielle du produit.",
                        max_length=254,
                    ),
                ),
                ("reply_to_email", models.EmailField(blank=True, max_length=254)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="Laisser vide tant qu'aucun logo officiel n'est disponible.",
                    ),
                ),
                ("contact_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="emailsend",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="bounce_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="from_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="in_reply_to",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="message_id",
            field=models.CharField(
                blank=True,
                help_text="En-tête Message-ID généré à l'envoi.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="references",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="reply_to_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="smtp_response",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="is_legacy",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="acquisition_maturity_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prospect",
            name="contactability_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prospect",
            name="icp_fit_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prospect",
            name="need_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prospect",
            name="outbound_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prospect",
            name="outbound_ineligible_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="prospect",
            name="predictneed_acquisition_score",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="prospect",
            name="predictneed_excluded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prospect",
            name="predictneed_exclusion_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="prospect",
            name="predictneed_grade",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                db_index=True,
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="predictneed_score_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="prospect",
            name="predictneed_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("identified", "Identifié"),
                    ("enriched", "Enrichi"),
                    ("qualified", "Qualifié"),
                    ("ready_to_contact", "Prêt à contacter"),
                    ("contacted", "Contacté"),
                    ("engaged", "Engagé"),
                    ("signed_up", "Inscrit"),
                    ("activated", "Activé"),
                    ("paying", "Client payant"),
                    ("nurture", "Nurture"),
                    ("lost", "Perdu"),
                    ("do_not_contact", "Ne plus contacter"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="timing_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emailsend",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("queued", "En file"),
                    ("sent", "Envoyé"),
                    ("failed", "Échec"),
                    ("blocked", "Bloqué"),
                    ("bounced", "Rejeté (bounce)"),
                    ("suppressed", "Supprimé (opposition)"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AgentBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_summary", models.TextField(blank=True)),
                ("why_this_company", models.TextField(blank=True)),
                ("detected_need", models.TextField(blank=True)),
                ("acquisition_maturity", models.TextField(blank=True)),
                ("relevant_signals", models.JSONField(blank=True, default=list)),
                ("competitors_detected", models.JSONField(blank=True, default=list)),
                ("recommended_contact", models.CharField(blank=True, max_length=255)),
                ("recommended_contact_reason", models.TextField(blank=True)),
                ("recommended_angle", models.TextField(blank=True)),
                ("objections_or_risks", models.JSONField(blank=True, default=list)),
                ("suggested_cta", models.CharField(blank=True, max_length=255)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("score_reasons", models.JSONField(blank=True, default=list)),
                ("evidence_urls", models.JSONField(blank=True, default=list)),
                ("next_best_action", models.CharField(blank=True, max_length=255)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_briefs",
                        to="prospects.prospect",
                    ),
                ),
                (
                    "icp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prospects.icpprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prospects.productprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("objective", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("ready", "Prêt (en attente de validation)"),
                            ("active", "Active"),
                            ("paused", "En pause"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("score_threshold", models.PositiveSmallIntegerField(default=65)),
                ("daily_send_limit", models.PositiveIntegerField(default=30)),
                ("total_limit", models.PositiveIntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="prospects.emailsequence",
                    ),
                ),
                (
                    "icp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="prospects.icpprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="prospects.productprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignProspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquisition_score_snapshot",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("grade", models.CharField(blank=True, max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identifié"),
                            ("selected", "Sélectionné"),
                            ("ready_to_contact", "Prêt à contacter"),
                            ("contacted", "Contacté"),
                            ("engaged", "Engagé"),
                            ("signed_up", "Inscrit"),
                            ("activated", "Activé"),
                            ("paying", "Client payant"),
                            ("nurture", "Nurture"),
                            ("lost", "Perdu"),
                            ("do_not_contact", "Ne plus contacter"),
                            ("excluded", "Exclu"),
                        ],
                        db_index=True,
                        default="identified",
                        max_length=20,
                    ),
                ),
                (
                    "tracking_token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("selected_at", models.DateTimeField(blank=True, null=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("last_engagement_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("excluded_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_brief",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prospects.agentbrief",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_prospects",
                        to="prospects.campaign",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_memberships",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ["-acquisition_score_snapshot"],
            },
        ),
        migrations.AddField(
            model_name="emailsend",
            name="campaign_prospect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_sends",
                to="prospects.campaignprospect",
            ),
        ),
        migrations.CreateModel(
            name="CompetitorDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("evidence", models.TextField(blank=True)),
                ("confidence", models.PositiveSmallIntegerField(default=70)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="prospects.competitor",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_detections",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("signup", "Inscription"),
                            ("activation", "Activation"),
                            ("paying", "Abonnement payant"),
                            ("cancelled", "Annulation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="Référence côté PredictNeed (jamais de données bancaires).",
                        max_length=160,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_events",
                        to="prospects.campaign",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_events",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "delay_days",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Délai depuis l'étape précédente (0 = premier email).",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=160)),
                ("active", models.BooleanField(default=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="prospects.emailsequence",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "order"],
            },
        ),
        migrations.AddField(
            model_name="emailsend",
            name="email_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prospects.emailstep",
            ),
        ),
        migrations.CreateModel(
            name="EmailVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("subject_template", models.CharField(max_length=255)),
                (
                    "cta_type",
                    models.CharField(
                        choices=[
                            ("simulator", "Tester le simulateur"),
                            ("product", "Voir PredictNeed IA"),
                            ("signup", "Créer un compte"),
                            ("reply", "Répondre à l'email"),
                        ],
                        default="simulator",
                        max_length=20,
                    ),
                ),
                ("cta_label_override", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100, help_text="Poids relatif pour la répartition A/B."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="prospects.emailstep",
                    ),
                ),
            ],
            options={
                "ordering": ["step", "name"],
            },
        ),
        migrations.AddField(
            model_name="emailsend",
            name="email_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prospects.emailvariant",
            ),
        ),
        migrations.CreateModel(
            name="EngagementEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("email_sent", "E-mail envoyé"),
                            ("email_failed", "E-mail en échec"),
                            ("link_clicked", "Lien cliqué"),
                            ("product_visited", "Visite du produit"),
                            ("simulator_started", "Simulateur démarré"),
                            ("simulator_completed", "Simulateur terminé"),
                            ("signup_started", "Inscription démarrée"),
                            ("signup_completed", "Inscription terminée"),
                            ("checkout_started", "Paiement démarré"),
                            ("subscription_activated", "Abonnement activé"),
                            ("subscription_cancelled", "Abonnement annulé"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("prospectpilot", "ProspectPilot"),
                            ("predictneed", "PredictNeed IA"),
                        ],
                        default="prospectpilot",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="prospects.campaign",
                    ),
                ),
                (
                    "campaign_prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="prospects.campaignprospect",
                    ),
                ),
                (
                    "email_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prospects.emailstep",
                    ),
                ),
                (
                    "email_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prospects.emailvariant",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_events",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddField(
            model_name="emailsequence",
            name="icp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sequences",
                to="prospects.icpprofile",
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="predictneed_icp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_prospects",
                to="prospects.icpprofile",
            ),
        ),
        migrations.AddField(
            model_name="icpprofile",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="icp_profiles",
                to="prospects.productprofile",
            ),
        ),
        migrations.AddField(
            model_name="emailsequence",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequences",
                to="prospects.productprofile",
            ),
        ),
        migrations.CreateModel(
            name="EmailComplianceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(blank=True, max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("postal_address", models.CharField(blank=True, max_length=500)),
                ("country", models.CharField(blank=True, max_length=120)),
                (
                    "company_registration_number",
                    models.CharField(
                        blank=True,
                        help_text="SIREN/SIRET si connu. Ne jamais inventer.",
                        max_length=60,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "privacy_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("dpo_email", models.EmailField(blank=True, max_length=254)),
                ("privacy_policy_url", models.URLField(blank=True)),
                ("legal_notice_url", models.URLField(blank=True)),
                ("data_rights_url", models.URLField(blank=True)),
                (
                    "default_legal_basis",
                    models.CharField(
                        blank=True,
                        help_text="Ex. intérêt légitime pour la prospection B2B — à faire valider juridiquement.",
                        max_length=255,
                    ),
                ),
                ("default_purpose", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_profile",
                        to="prospects.productprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["product__name"],
            },
        ),
        migrations.CreateModel(
            name="CompanySearchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("manual", "Recherche manuelle"),
                            ("acquisition", "Acquisition PredictNeed IA"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("campaign_name", models.CharField(blank=True, max_length=160)),
                ("criteria", models.JSONField(blank=True, default=dict)),
                ("volume_max_candidates", models.PositiveIntegerField(default=500)),
                ("volume_max_enrich", models.PositiveIntegerField(default=100)),
                ("score_threshold", models.PositiveSmallIntegerField(default=50)),
                (
                    "ranking_option",
                    models.CharField(
                        blank=True, default="priority_score", max_length=40
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("queued", "En file"),
                            ("running", "En cours"),
                            ("paused", "En pause"),
                            ("done", "Terminé"),
                            ("failed", "Échec"),
                            ("cancelled", "Annulé"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("registry_count", models.PositiveIntegerField(default=0)),
                ("preselected_count", models.PositiveIntegerField(default=0)),
                ("with_site_count", models.PositiveIntegerField(default=0)),
                ("enriched_count", models.PositiveIntegerField(default=0)),
                ("with_email_count", models.PositiveIntegerField(default=0)),
                ("qualified_a_count", models.PositiveIntegerField(default=0)),
                ("qualified_b_count", models.PositiveIntegerField(default=0)),
                ("qualified_c_count", models.PositiveIntegerField(default=0)),
                ("not_eligible_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("current_stage", models.CharField(blank=True, max_length=40)),
                (
                    "cursor",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Position de reprise (page registre, index candidat...).",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "icp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_runs",
                        to="prospects.icpprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_runs",
                        to="prospects.productprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_templates",
                to="prospects.productprofile",
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="predictneed_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prospects",
                to="prospects.productprofile",
            ),
        ),
        migrations.CreateModel(
            name="ProspectSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signal_type", models.CharField(db_index=True, max_length=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("icp", "ICP"),
                            ("acquisition", "Acquisition"),
                            ("conversion", "Conversion"),
                            ("analytics", "Analytics"),
                            ("advertising", "Publicité"),
                            ("crm", "CRM"),
                            ("competitor", "Concurrent"),
                            ("contactability", "Contactabilité"),
                            ("growth", "Croissance"),
                            ("timing", "Timing"),
                            ("risk", "Risque"),
                        ],
                        default="acquisition",
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("evidence", models.TextField(blank=True)),
                ("confidence", models.PositiveSmallIntegerField(default=70)),
                ("score_impact", models.SmallIntegerField(default=0)),
                ("positive", models.BooleanField(default=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ["-positive", "-score_impact"],
            },
        ),
        migrations.CreateModel(
            name="ProspectTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technology", models.CharField(db_index=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("analytics", "Analytics"),
                            ("advertising", "Publicité"),
                            ("crm", "CRM / Marketing automation"),
                            ("scheduling", "Prise de RDV / formulaires"),
                            ("support", "Support / chat"),
                            ("ecommerce", "E-commerce"),
                            ("behaviour_analytics", "Analyse comportementale"),
                            ("visitor_intelligence", "Intelligence visiteurs B2B"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("evidence", models.TextField(blank=True)),
                ("confidence", models.PositiveSmallIntegerField(default=70)),
                ("is_active", models.BooleanField(default=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "technology"],
            },
        ),
        migrations.CreateModel(
            name="RevenueAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "mrr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="EUR", max_length=8)),
                (
                    "attributed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_attributions",
                        to="prospects.campaign",
                    ),
                ),
                (
                    "conversion_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribution",
                        to="prospects.conversionevent",
                    ),
                ),
                (
                    "email_sequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prospects.emailsequence",
                    ),
                ),
                (
                    "email_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prospects.emailstep",
                    ),
                ),
                (
                    "email_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prospects.emailvariant",
                    ),
                ),
                (
                    "icp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prospects.icpprofile",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_attributions",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ["-attributed_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siren", models.CharField(db_index=True, max_length=9)),
                ("siret", models.CharField(blank=True, db_index=True, max_length=14)),
                ("name", models.CharField(max_length=255)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("pre_score", models.PositiveSmallIntegerField(default=0)),
                ("pre_score_reasons", models.JSONField(blank=True, default=list)),
                ("site_url", models.URLField(blank=True)),
                ("site_confidence", models.PositiveSmallIntegerField(default=0)),
                ("quick_scan_data", models.JSONField(blank=True, default=dict)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("outbound_eligible", models.BooleanField(default=False)),
                (
                    "outbound_ineligible_reason",
                    models.CharField(blank=True, max_length=255),
                ),
                ("final_score", models.PositiveSmallIntegerField(default=0)),
                ("grade", models.CharField(blank=True, max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("preselected", "Présélectionné"),
                            ("rejected_prescore", "Rejeté (pré-score)"),
                            ("site_found", "Site trouvé"),
                            ("no_site", "Site introuvable"),
                            ("scanned", "Analysé (quick scan)"),
                            ("enriched", "Enrichi"),
                            ("scored", "Scoré"),
                            ("converted", "Converti en prospect"),
                            ("not_eligible", "Non éligible"),
                            ("error", "Erreur"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_candidate_origins",
                        to="prospects.prospect",
                    ),
                ),
                (
                    "search_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="prospects.companysearchrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-final_score", "-pre_score"],
            },
        ),
        migrations.CreateModel(
            name="SearchPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filtres registre additionnels (zone, etc).",
                    ),
                ),
                ("volume_max_candidates", models.PositiveIntegerField(default=500)),
                ("volume_max_enrich", models.PositiveIntegerField(default=100)),
                ("score_threshold", models.PositiveSmallIntegerField(default=50)),
                ("active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "icp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_presets",
                        to="prospects.icpprofile",
                    ),
                ),
                (
                    "periodic_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_preset",
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_presets",
                        to="prospects.productprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="companysearchrun",
            name="preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_runs",
                to="prospects.searchpreset",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignprospect",
            constraint=models.UniqueConstraint(
                fields=("campaign", "prospect"), name="unique_prospect_per_campaign"
            ),
        ),
        migrations.AddConstraint(
            model_name="competitordetection",
            constraint=models.UniqueConstraint(
                fields=("prospect", "competitor"), name="unique_competitor_per_prospect"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailstep",
            constraint=models.UniqueConstraint(
                fields=("sequence", "order"), name="unique_step_order_per_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="engagementevent",
            index=models.Index(
                fields=["event_type", "occurred_at"],
                name="prospects_e_event_t_09b2ff_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="icpprofile",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="unique_icp_name_per_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="prospecttechnology",
            constraint=models.UniqueConstraint(
                fields=("prospect", "technology"), name="unique_technology_per_prospect"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchcandidate",
            constraint=models.UniqueConstraint(
                fields=("search_run", "siren"), name="unique_candidate_per_run_siren"
            ),
        ),
    ]
