# Generated by Django 5.2.4 on 2026-08-18 18:55
#
# Mission 5, section 3 — migration purement additive (aucune suppression, aucune
# perte de données) : ajoute selected_for_prospecting/selected_at à Prospect et
# error_count à CompanySearchRun, puis backfill selon la valeur RÉELLE du champ
# `source` déjà en production (auditée avant migration, jamais devinée) :
#   - source != "acquisition_pipeline_predictneed" (prospects historiques,
#     importés, manuels) -> déjà considérés sélectionnés (selected_at = created_at) ;
#   - source == "acquisition_pipeline_predictneed" (candidats techniques du
#     pipeline d'acquisition) -> pas encore sélectionnés par un humain, mais
#     aucune de leurs données n'est touchée ni supprimée.

from django.db import migrations, models


def backfill_selected_for_prospecting(apps, schema_editor):
    Prospect = apps.get_model("prospects", "Prospect")
    Prospect.objects.exclude(source="acquisition_pipeline_predictneed").update(
        selected_for_prospecting=True,
    )
    db_alias = schema_editor.connection.alias
    Prospect.objects.using(db_alias).exclude(
        source="acquisition_pipeline_predictneed"
    ).update(selected_at=models.F("created_at"))


def noop_reverse(apps, schema_editor):
    """Pas de retour arrière destructif : on laisse simplement les champs à
    leur valeur, ils seront supprimés par le AddField inverse le cas échéant."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "prospects",
            "0004_competitor_emailsequence_icpprofile_productprofile_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="companysearchrun",
            name="error_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prospect",
            name="selected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="selected_for_prospecting",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill_selected_for_prospecting, noop_reverse),
    ]
