# Generated by Django 5.2.4 on 2026-08-19 00:08
#
# Correctif pré-production : crée l'index de selected_for_prospecting dans sa
# propre transaction, séparée de 0005 (colonnes + backfill). 0005 échouait en
# production (Postgres 18) avec "cannot CREATE INDEX ... because it has
# pending trigger events" quand le CREATE INDEX partageait la transaction du
# AddField/RunPython. Purement additive, aucune donnée touchée.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0005_mission5_selection_and_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='selected_for_prospecting',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
