# Generated by Django 5.2.4 on 2026-08-19 14:41
# Corrigé suite à audit indépendant (jamais déployée avant ce correctif) :
#
# 1. Une migration ne doit JAMAIS importer du code applicatif
#    (`prospects.services.signals`) : ce module peut évoluer ou disparaître
#    dans le futur, ce qui casserait cette migration historique lors d'un
#    replay. `_frozen_category_to_group` et `_frozen_signal_fingerprint`
#    ci-dessous sont des copies figées, indépendantes du code applicatif
#    actuel — elles ne changent plus jamais, même si services/signals.py
#    change.
# 2. `source_kind` historique corrigé : "technologie ≠ website". Avant ce
#    correctif, TOUT l'historique était backfillé "website", y compris les
#    signaux qui viennent en réalité de build_signals_from_technologies
#    (analytics/advertising/crm/competitor/acquisition — les seules
#    catégories que cette fonction produit, vérifié dans le code au moment
#    d'écrire ce correctif). Ces catégories sont maintenant backfillées
#    "technology" ; le reste (icp/contactability/growth/conversion/risk,
#    qui ne viennent que de build_signals_from_quick_scan) reste "website".
# 3. `signal_group` : la table de correspondance catégorie -> groupe utilisée
#    ici classe "growth"/"conversion" comme FIT (caractéristiques statiques
#    du site — formulaire de contact, lead magnet... — jamais une intention
#    d'achat actuelle), pas "intent". Conséquence vérifiable : AUCUNE
#    catégorie historique ne produit signal_group="intent" (seule "timing"
#    y est associée, catégorie jamais utilisée par le code de production
#    avant Mission 6) — donc aucun signal statique ancien ne se retrouve
#    artificiellement classé comme intention récente.
#
# Colonnes + backfill uniquement, PAS d'index (leçon de la migration 0005 :
# la création d'index/contrainte est déplacée en 0008, dans sa propre
# transaction, pour ne jamais répéter l'incident production "cannot CREATE
# INDEX ... because it has pending trigger events"). Purement additif :
# aucune colonne supprimée, aucune ligne ProspectSignal supprimée.
#
# observed_at = detected_at existant (meilleure donnée disponible pour un
# fait FIT — la fraîcheur n'affecte pas les signaux FIT, seuls les signaux
# intent en dépendent, et aucun signal historique n'est intent, voir point 3).
import hashlib

from django.db import migrations, models

# Copie figée de CATEGORY_TO_GROUP au moment de ce correctif — ne JAMAIS
# faire pointer ceci vers services/signals.CATEGORY_TO_GROUP (voir point 1
# ci-dessus). Toute évolution future du mapping applicatif n'a AUCUN effet
# sur ce backfill historique, par construction.
_FROZEN_CATEGORY_TO_GROUP = {
    "icp": "fit",
    "contactability": "fit",
    "analytics": "fit",
    "advertising": "fit",
    "crm": "fit",
    "acquisition": "fit",
    "competitor": "fit",
    "growth": "fit",
    "conversion": "fit",
    "timing": "intent",
    "risk": "risk",
}

# Catégories produites exclusivement par build_signals_from_technologies au
# moment de ce correctif (vérifié dans le code, pas deviné) -> source_kind
# historique "technology". Toutes les autres catégories ne viennent que de
# build_signals_from_quick_scan -> "website".
_TECHNOLOGY_ORIGIN_CATEGORIES = {"analytics", "advertising", "crm", "competitor", "acquisition"}


def _frozen_signal_fingerprint(signal_type, value="", evidence=""):
    """Copie figée de signal_fingerprint() — même algorithme, gelé ici pour
    toujours produire le même résultat sur ce backfill historique, quelle
    que soit l'évolution future de services/signals.py."""
    raw = f"{signal_type}|{(value or '').strip().lower()}|{(evidence or '').strip().lower()[:200]}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:32]


def backfill_signal_fields(apps, schema_editor):
    ProspectSignal = apps.get_model("prospects", "ProspectSignal")
    db_alias = schema_editor.connection.alias
    for signal in ProspectSignal.objects.using(db_alias).all():
        signal.signal_group = _FROZEN_CATEGORY_TO_GROUP.get(signal.category, "fit")
        signal.source_kind = "technology" if signal.category in _TECHNOLOGY_ORIGIN_CATEGORIES else "website"
        signal.observed_at = signal.detected_at
        signal.fingerprint = _frozen_signal_fingerprint(signal.signal_type, signal.value, signal.evidence)
        signal.save(update_fields=["signal_group", "source_kind", "observed_at", "fingerprint"])


def noop_reverse(apps, schema_editor):
    """Pas de retour arrière destructif — les colonnes seront simplement
    supprimées par l'AddField inverse le cas échéant."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0006_mission5_selected_for_prospecting_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="engagement_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prospect",
            name="engagement_score_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="prospect",
            name="intent_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prospect",
            name="intent_score_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="prospect",
            name="scores_computed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospectsignal",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="prospectsignal",
            name="observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospectsignal",
            name="signal_group",
            field=models.CharField(
                choices=[
                    ("fit", "Fit"),
                    ("intent", "Intent"),
                    ("engagement", "Engagement"),
                    ("risk", "Risque"),
                ],
                default="fit",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prospectsignal",
            name="source_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registry", "Registre officiel"),
                    ("website", "Site web"),
                    ("technology", "Technologie détectée"),
                    ("open_web", "Web ouvert"),
                    ("social", "Réseau social"),
                    ("linkedin", "LinkedIn"),
                    ("campaign", "Campagne ProspectPilot"),
                    ("predictneed", "PredictNeed IA"),
                    ("manual", "Ajout manuel"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_signal_fields, noop_reverse),
    ]
