# Generated by Django 5.2.4 on 2026-08-19 14:41
#
# Mission 6 — colonnes + backfill uniquement, PAS d'index (leçon de la
# migration 0005 : la création d'index/contrainte est déplacée en 0008, dans
# sa propre transaction, pour ne jamais répéter l'incident production
# "cannot CREATE INDEX ... because it has pending trigger events"). Purement
# additif : aucune colonne supprimée, aucune ligne ProspectSignal supprimée.
#
# Backfill ProspectSignal (233 lignes en production au moment d'écrire ceci) :
# - signal_group déduit de `category` (CATEGORY_TO_GROUP, mapping partagé
#   avec services/signals.py — jamais deux formules différentes) ;
# - source_kind = "website" pour tout l'historique : tous les signaux
#   existants viennent de build_signals_from_technologies/build_signals_from_quick_scan,
#   qui scannent uniquement le site du prospect (vérifié dans le code, pas deviné) ;
# - observed_at = detected_at existant (meilleure donnée disponible, jamais inventée) ;
# - fingerprint = signal_fingerprint(signal_type, value, evidence), la même
#   fonction que celle utilisée pour tout nouveau signal.

from django.db import migrations, models

from prospects.services.signals import CATEGORY_TO_GROUP, signal_fingerprint


def backfill_signal_fields(apps, schema_editor):
    ProspectSignal = apps.get_model("prospects", "ProspectSignal")
    db_alias = schema_editor.connection.alias
    for signal in ProspectSignal.objects.using(db_alias).all():
        signal.signal_group = CATEGORY_TO_GROUP.get(signal.category, "fit")
        signal.source_kind = "website"
        signal.observed_at = signal.detected_at
        signal.fingerprint = signal_fingerprint(signal.signal_type, signal.value, signal.evidence)
        signal.save(update_fields=["signal_group", "source_kind", "observed_at", "fingerprint"])


def noop_reverse(apps, schema_editor):
    """Pas de retour arrière destructif — les colonnes seront simplement
    supprimées par l'AddField inverse le cas échéant."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0006_mission5_selected_for_prospecting_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="engagement_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prospect",
            name="engagement_score_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="prospect",
            name="intent_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prospect",
            name="intent_score_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="prospect",
            name="scores_computed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospectsignal",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="prospectsignal",
            name="observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospectsignal",
            name="signal_group",
            field=models.CharField(
                choices=[
                    ("fit", "Fit"),
                    ("intent", "Intent"),
                    ("engagement", "Engagement"),
                    ("risk", "Risque"),
                ],
                default="fit",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prospectsignal",
            name="source_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registry", "Registre officiel"),
                    ("website", "Site web"),
                    ("technology", "Technologie détectée"),
                    ("open_web", "Web ouvert"),
                    ("social", "Réseau social"),
                    ("linkedin", "LinkedIn"),
                    ("campaign", "Campagne ProspectPilot"),
                    ("predictneed", "PredictNeed IA"),
                    ("manual", "Ajout manuel"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_signal_fields, noop_reverse),
    ]
