# Generated by Django 5.2.4 on 2026-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0007_mission6_signal_and_scores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prospect",
            name="engagement_score",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="intent_score",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddConstraint(
            model_name="prospectsignal",
            constraint=models.UniqueConstraint(
                fields=("prospect", "signal_type", "source_kind", "fingerprint"),
                name="unique_signal_identity_per_prospect",
            ),
        ),
    ]
