# Generated by Django 5.2.4 on 2026-08-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0008_mission6_signal_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="contactlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="contactlog",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("sent", "Envoyé"),
                    ("opened", "Ouvert"),
                    ("replied", "Réponse"),
                    ("meeting", "Rendez-vous"),
                    ("proposal", "Proposition"),
                    ("won", "Client"),
                    ("lost", "Refus"),
                    ("optout", "Opposition"),
                    ("invitation_prepared", "Invitation préparée (non envoyée)"),
                    ("invitation_sent", "Invitation envoyée"),
                    ("invitation_accepted", "Invitation acceptée"),
                    ("invitation_declined", "Invitation refusée ou expirée"),
                    ("message_prepared", "Message préparé (non envoyé)"),
                ],
                default="sent",
                max_length=30,
            ),
        ),
    ]
