# Generated by Django 5.2.4 on 2026-08-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0009_mission6_linkedin_contactlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignprospect",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="prospects.emailstep",
            ),
        ),
        migrations.AddField(
            model_name="campaignprospect",
            name="current_step_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactlog",
            name="campaign_prospect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_logs",
                to="prospects.campaignprospect",
            ),
        ),
        migrations.AddField(
            model_name="contactlog",
            name="email_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prospects.emailstep",
            ),
        ),
        migrations.AddField(
            model_name="emailstep",
            name="advance_condition",
            field=models.CharField(
                choices=[
                    ("always", "Toujours (délai seul)"),
                    ("linkedin_accepted", "Invitation LinkedIn acceptée"),
                ],
                default="always",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="emailstep",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "E-mail"),
                    ("linkedin_connect", "Invitation LinkedIn"),
                    ("linkedin_message", "Message LinkedIn"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
