# Generated by Django 5.2.4 on 2026-08-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0010_mission6_multichannel_sequencing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("intent_threshold_crossed", "Seuil d'intention franchi"),
                            ("strong_signal", "Signal fort détecté"),
                            ("new_engagement", "Nouvel engagement PredictNeed"),
                            ("reactivated", "Prospect réactivé après inactivité"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("dedup_key", models.CharField(max_length=120)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prospect", "alert_type", "dedup_key"),
                        name="unique_alert_dedup",
                    )
                ],
            },
        ),
    ]
