# Generated by Django 5.2.4 on 2026-08-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0011_mission6_alerts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactlog",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("sent", "Envoyé"),
                    ("opened", "Ouvert"),
                    ("replied", "Réponse"),
                    ("meeting", "Rendez-vous"),
                    ("proposal", "Proposition"),
                    ("won", "Client"),
                    ("lost", "Refus"),
                    ("optout", "Opposition"),
                    ("invitation_prepared", "Invitation préparée (non envoyée)"),
                    ("invitation_sent", "Invitation envoyée"),
                    ("invitation_accepted", "Invitation acceptée"),
                    ("invitation_declined", "Invitation refusée ou expirée"),
                    ("message_prepared", "Message préparé (non envoyé)"),
                    ("invitation_failed", "Échec d'envoi de l'invitation"),
                    ("message_failed", "Échec d'envoi du message"),
                ],
                default="sent",
                max_length=30,
            ),
        ),
    ]
