# Generated by Django 5.2.4 on 2026-08-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0013_mission6_audit_round2_icp_weights_backfill"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prospect",
            options={"ordering": ["-predictneed_acquisition_score", "-updated_at"]},
        ),
        migrations.AlterField(
            model_name="campaignprospect",
            name="status",
            field=models.CharField(
                choices=[
                    ("identified", "Identifié"),
                    ("selected", "Sélectionné"),
                    ("ready_to_contact", "Prêt à contacter"),
                    ("contacted", "Contacté"),
                    ("engaged", "Engagé"),
                    ("signed_up", "Inscrit"),
                    ("activated", "Activé"),
                    ("paying", "Client payant"),
                    ("churned", "Client perdu (résiliation)"),
                    ("nurture", "Nurture"),
                    ("lost", "Perdu"),
                    ("do_not_contact", "Ne plus contacter"),
                    ("excluded", "Exclu"),
                ],
                db_index=True,
                default="identified",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="icpprofile",
            name="weights",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Pondération icp_fit/need/acquisition_maturity/contactability/timing/intent/engagement (somme=100). Vide = valeurs par défaut (DEFAULT_ICP_WEIGHTS).",
            ),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="predictneed_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("identified", "Identifié"),
                    ("enriched", "Enrichi"),
                    ("qualified", "Qualifié"),
                    ("ready_to_contact", "Prêt à contacter"),
                    ("contacted", "Contacté"),
                    ("engaged", "Engagé"),
                    ("signed_up", "Inscrit"),
                    ("activated", "Activé"),
                    ("paying", "Client payant"),
                    ("churned", "Client perdu (résiliation)"),
                    ("nurture", "Nurture"),
                    ("lost", "Perdu"),
                    ("do_not_contact", "Ne plus contacter"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
