# Generated by Django 5.2.4 on 2026-08-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0014_mission6_audit_round3_stage_and_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactperson",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Non vérifié"),
                    ("format_valid", "Format valide"),
                    ("public_source_confirmed", "Trouvé sur une page publique"),
                    ("domain_mx_valid", "Domaine avec MX valide"),
                    ("pattern_inferred", "Motif déduit (non confirmé)"),
                    ("deliverability_unknown", "Délivrabilité inconnue"),
                    ("verified", "Vérifié"),
                    ("invalid", "Invalide"),
                    ("blocked", "Bloqué"),
                    ("conflict", "Conflit"),
                ],
                db_index=True,
                default="unverified",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="prospectevidence",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Non vérifié"),
                    ("format_valid", "Format valide"),
                    ("public_source_confirmed", "Trouvé sur une page publique"),
                    ("domain_mx_valid", "Domaine avec MX valide"),
                    ("pattern_inferred", "Motif déduit (non confirmé)"),
                    ("deliverability_unknown", "Délivrabilité inconnue"),
                    ("verified", "Vérifié"),
                    ("invalid", "Invalide"),
                    ("blocked", "Bloqué"),
                    ("conflict", "Conflit"),
                ],
                db_index=True,
                default="unverified",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="publicemail",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Non vérifié"),
                    ("format_valid", "Format valide"),
                    ("public_source_confirmed", "Trouvé sur une page publique"),
                    ("domain_mx_valid", "Domaine avec MX valide"),
                    ("pattern_inferred", "Motif déduit (non confirmé)"),
                    ("deliverability_unknown", "Délivrabilité inconnue"),
                    ("verified", "Vérifié"),
                    ("invalid", "Invalide"),
                    ("blocked", "Bloqué"),
                    ("conflict", "Conflit"),
                ],
                db_index=True,
                default="format_valid",
                max_length=30,
            ),
        ),
    ]
