# Generated by Django 5.2.4 on 2026-08-23 14:23

import django.db.models.deletion
import prospects.models.acquisition
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0015_mission7_email_verification_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="planning_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="first_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="last_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="open_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emailsend",
            name="open_tracking_token",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="engagementevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("email_sent", "E-mail envoyé"),
                    ("email_failed", "E-mail en échec"),
                    ("link_clicked", "Lien cliqué"),
                    ("email_opened", "Ouverture détectée (indicative)"),
                    ("email_replied", "Réponse reçue"),
                    ("product_visited", "Visite du produit"),
                    ("simulator_started", "Simulateur démarré"),
                    ("simulator_completed", "Simulateur terminé"),
                    ("signup_started", "Inscription démarrée"),
                    ("signup_completed", "Inscription terminée"),
                    ("checkout_started", "Paiement démarré"),
                    ("subscription_activated", "Abonnement activé"),
                    ("subscription_cancelled", "Abonnement annulé"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="EmailAutomationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(default="Europe/Paris", max_length=64),
                ),
                (
                    "send_window_start",
                    models.TimeField(
                        default=prospects.models.acquisition._default_window_start
                    ),
                ),
                (
                    "send_window_end",
                    models.TimeField(
                        default=prospects.models.acquisition._default_window_end
                    ),
                ),
                ("new_contacts_per_day", models.PositiveSmallIntegerField(default=5)),
                ("daily_total_limit", models.PositiveSmallIntegerField(default=10)),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Réglages du Planning e-mail",
                "verbose_name_plural": "Réglages du Planning e-mail",
            },
        ),
        migrations.CreateModel(
            name="PlannedEmailContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("html_body", models.TextField()),
                ("text_body", models.TextField()),
                (
                    "content_hash",
                    models.CharField(
                        help_text="Empreinte du rendu au moment de la validation, pour détecter un contenu devenu obsolète.",
                        max_length=64,
                    ),
                ),
                (
                    "open_tracking_token",
                    models.CharField(
                        blank=True,
                        help_text="Token du pixel d'ouverture déjà intégré dans html_body — recopié sur EmailSend à l'envoi réel.",
                        max_length=64,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        help_text="Jour ouvré prévu (déjà ajusté week-end)."
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_validate", "À valider"),
                            ("validated", "Validé"),
                            ("stale", "Contenu modifié depuis validation"),
                        ],
                        default="to_validate",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign_prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_contents",
                        to="prospects.campaignprospect",
                    ),
                ),
                (
                    "email_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prospects.emailstep",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign_prospect", "email_step"),
                        name="unique_planned_content_per_step",
                    )
                ],
            },
        ),
    ]
