# Generated by Django 5.2.4 on 2026-08-23 14:26
"""Section F/J — enregistre les deux tâches planifiées Celery Beat pour le
scheduler d'automatisation email et le polling IMAP des réponses.

IMPORTANT (sécurité de déploiement) : les deux PeriodicTask sont créées avec
`enabled=False`. Au premier déploiement de cette mission, aucune campagne
historique/préexistante ne devient automatiquement éligible à un envoi
simplement parce que cette migration s'applique — le scheduler ne tournera
réellement qu'après une activation explicite et séparée (dans l'admin
Django, django_celery_beat), jamais comme effet de bord de cette migration.
"""
from django.db import migrations


def create_periodic_tasks(apps, schema_editor):
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    five_min, _ = IntervalSchedule.objects.get_or_create(every=5, period="minutes")
    ten_min, _ = IntervalSchedule.objects.get_or_create(every=10, period="minutes")

    PeriodicTask.objects.get_or_create(
        name="Planning e-mail — scheduler automatisation",
        defaults={
            "interval": five_min,
            "task": "prospects.tasks.run_email_planning_scheduler_task",
            "enabled": False,
        },
    )
    PeriodicTask.objects.get_or_create(
        name="Planning e-mail — polling réponses IMAP",
        defaults={
            "interval": ten_min,
            "task": "prospects.tasks.poll_inbound_replies_task",
            "enabled": False,
        },
    )


def remove_periodic_tasks(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(
        name__in=[
            "Planning e-mail — scheduler automatisation",
            "Planning e-mail — polling réponses IMAP",
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0016_mission8_email_automation_planning"),
        ("django_celery_beat", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_periodic_tasks, remove_periodic_tasks),
    ]
