# Generated by Django 5.2.4 on 2026-08-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0017_mission8_email_automation_periodic_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedInboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("result", models.CharField(blank=True, max_length=30)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="emailsend",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailsend",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("queued", "En file"),
                    ("sent", "Envoyé"),
                    ("failed", "Échec"),
                    (
                        "permanently_failed",
                        "Échec permanent (nombre max de tentatives atteint)",
                    ),
                    ("blocked", "Bloqué"),
                    ("bounced", "Rejeté (bounce)"),
                    ("suppressed", "Supprimé (opposition)"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
