# Generated by Django 5.2.4 on 2026-08-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0018_mission8_correctif_audit_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plannedemailcontent",
            name="open_tracking_token",
        ),
        migrations.AddField(
            model_name="emailautomationsettings",
            name="last_seen_uid",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Dernier UID IMAP déjà balayé (curseur best-effort) — 0 force un SEARCH ALL complet.",
            ),
        ),
        migrations.AddField(
            model_name="plannedemailcontent",
            name="test_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Horodatage du dernier test EmailSend réussi pour ce contenu.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plannedemailcontent",
            name="tested_content_hash",
            field=models.CharField(
                blank=True,
                help_text="content_hash au moment du dernier test EmailSend réussi. La validation exige tested_content_hash == content_hash.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="processedinboundmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente de traitement"),
                    ("processing", "En cours de traitement"),
                    ("processed", "Traité"),
                    ("failed", "Échec (réessayable)"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="processedinboundmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="plannedemailcontent",
            name="content_hash",
            field=models.CharField(
                help_text="Empreinte du rendu (contenu visible, sans pixel) au moment de la préparation.",
                max_length=64,
            ),
        ),
    ]
