# Generated by Django 5.2.4 on 2026-08-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0019_mission8_correctif_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedemailcontent",
            name="manually_edited_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Renseigné dès qu'une modification manuelle (sujet/texte) a été enregistrée sur cette ligne précise — le contenu n'est alors plus jamais signalé automatiquement comme périmé (voir is_content_stale) : la version humaine fait foi.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plannedemailcontent",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_validate", "À relire"),
                    ("modified", "Modifié — à reprogrammer"),
                    ("validated", "Programmé"),
                    ("stale", "Modifié — à reprogrammer"),
                ],
                default="to_validate",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plannedemailcontent",
            name="tested_content_hash",
            field=models.CharField(
                blank=True,
                help_text="content_hash au moment du dernier test EmailSend réussi — purement informatif (badge « Testé ») depuis le workflow final : ne conditionne plus la validation.",
                max_length=64,
            ),
        ),
    ]
