# Generated by Django 5.2.4 on 2026-08-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0020_mission8_prepared_email_editor"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedemailcontent",
            name="editable_body_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Source éditoriale en texte brut du corps rédactionnel actuel (paragraphes séparés par une ligne vide), hors salutation/CTA/lien technique/ligne de réponse automatique/signature/footer conformité/tracking — ce sont ces éléments-là, et eux seuls, qui restent protégés et jamais éditables. Préremplit le formulaire de modification (workflow live preview) : jamais vide tant qu'un contenu préparé existe. Recalculée intégralement à chaque prepare_planned_content() (le rendu auto redevient la référence) et à chaque apply_manual_edit() (devient alors exactement le texte saisi par l'utilisatrice).",
            ),
        ),
    ]
